dataset: atis
db_id: atis
train_data_path : dataset/atis/atis_train.json
valid_data_path : dataset/atis/atis_valid.json

exp_name : atis_t5-3b-picard
model_name: tscholak/cxmefzzi
mode: train
load_model_path: 
train_batch_size: 2
accumulation_steps: 16
eval_every_step: 500
eval_batch_size: 2
training_data_ratio: 1.0
bf16: true
optim: adam
lr: 0.0001

tables_path: dataset/atis/tables.json
add_schema: true

use_wandb: false
wandb_project: reliable-semantic-parsing